# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetMspSparkV1alpha1SessionResult',
    'AwaitableGetMspSparkV1alpha1SessionResult',
    'get_msp_spark_v1alpha1_session',
    'get_msp_spark_v1alpha1_session_output',
]

@pulumi.output_type
class GetMspSparkV1alpha1SessionResult:
    """
    A collection of values returned by getMspSparkV1alpha1Session.
    """
    def __init__(__self__, created_at=None, description=None, driver=None, executor=None, file_uris=None, id=None, jar_uris=None, labels=None, metadata=None, name=None, packages=None, parent_id=None, python=None, resource_version=None, spark_conf=None, spark_version=None, status=None, updated_at=None):
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if description and not isinstance(description, str):
            raise TypeError("Expected argument 'description' to be a str")
        pulumi.set(__self__, "description", description)
        if driver and not isinstance(driver, dict):
            raise TypeError("Expected argument 'driver' to be a dict")
        pulumi.set(__self__, "driver", driver)
        if executor and not isinstance(executor, dict):
            raise TypeError("Expected argument 'executor' to be a dict")
        pulumi.set(__self__, "executor", executor)
        if file_uris and not isinstance(file_uris, list):
            raise TypeError("Expected argument 'file_uris' to be a list")
        pulumi.set(__self__, "file_uris", file_uris)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if jar_uris and not isinstance(jar_uris, list):
            raise TypeError("Expected argument 'jar_uris' to be a list")
        pulumi.set(__self__, "jar_uris", jar_uris)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if packages and not isinstance(packages, list):
            raise TypeError("Expected argument 'packages' to be a list")
        pulumi.set(__self__, "packages", packages)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if python and not isinstance(python, dict):
            raise TypeError("Expected argument 'python' to be a dict")
        pulumi.set(__self__, "python", python)
        if resource_version and not isinstance(resource_version, float):
            raise TypeError("Expected argument 'resource_version' to be a float")
        pulumi.set(__self__, "resource_version", resource_version)
        if spark_conf and not isinstance(spark_conf, dict):
            raise TypeError("Expected argument 'spark_conf' to be a dict")
        pulumi.set(__self__, "spark_conf", spark_conf)
        if spark_version and not isinstance(spark_version, str):
            raise TypeError("Expected argument 'spark_version' to be a str")
        pulumi.set(__self__, "spark_version", spark_version)
        if status and not isinstance(status, dict):
            raise TypeError("Expected argument 'status' to be a dict")
        pulumi.set(__self__, "status", status)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> str:
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter
    def description(self) -> str:
        return pulumi.get(self, "description")

    @property
    @pulumi.getter
    def driver(self) -> 'outputs.GetMspSparkV1alpha1SessionDriverResult':
        return pulumi.get(self, "driver")

    @property
    @pulumi.getter
    def executor(self) -> 'outputs.GetMspSparkV1alpha1SessionExecutorResult':
        return pulumi.get(self, "executor")

    @property
    @pulumi.getter(name="fileUris")
    def file_uris(self) -> Sequence[str]:
        return pulumi.get(self, "file_uris")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter(name="jarUris")
    def jar_uris(self) -> Sequence[str]:
        return pulumi.get(self, "jar_uris")

    @property
    @pulumi.getter
    def labels(self) -> Mapping[str, str]:
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter
    def metadata(self) -> 'outputs.GetMspSparkV1alpha1SessionMetadataResult':
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter
    def packages(self) -> Sequence[str]:
        return pulumi.get(self, "packages")

    @property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> str:
        return pulumi.get(self, "parent_id")

    @property
    @pulumi.getter
    def python(self) -> 'outputs.GetMspSparkV1alpha1SessionPythonResult':
        return pulumi.get(self, "python")

    @property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> float:
        return pulumi.get(self, "resource_version")

    @property
    @pulumi.getter(name="sparkConf")
    def spark_conf(self) -> Mapping[str, str]:
        return pulumi.get(self, "spark_conf")

    @property
    @pulumi.getter(name="sparkVersion")
    def spark_version(self) -> str:
        return pulumi.get(self, "spark_version")

    @property
    @pulumi.getter
    def status(self) -> 'outputs.GetMspSparkV1alpha1SessionStatusResult':
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> str:
        return pulumi.get(self, "updated_at")


class AwaitableGetMspSparkV1alpha1SessionResult(GetMspSparkV1alpha1SessionResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetMspSparkV1alpha1SessionResult(
            created_at=self.created_at,
            description=self.description,
            driver=self.driver,
            executor=self.executor,
            file_uris=self.file_uris,
            id=self.id,
            jar_uris=self.jar_uris,
            labels=self.labels,
            metadata=self.metadata,
            name=self.name,
            packages=self.packages,
            parent_id=self.parent_id,
            python=self.python,
            resource_version=self.resource_version,
            spark_conf=self.spark_conf,
            spark_version=self.spark_version,
            status=self.status,
            updated_at=self.updated_at)


def get_msp_spark_v1alpha1_session(id: Optional[str] = None,
                                   name: Optional[str] = None,
                                   parent_id: Optional[str] = None,
                                   opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetMspSparkV1alpha1SessionResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getMspSparkV1alpha1Session:getMspSparkV1alpha1Session', __args__, opts=opts, typ=GetMspSparkV1alpha1SessionResult, package_ref=_utilities.get_package()).value

    return AwaitableGetMspSparkV1alpha1SessionResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        description=pulumi.get(__ret__, 'description'),
        driver=pulumi.get(__ret__, 'driver'),
        executor=pulumi.get(__ret__, 'executor'),
        file_uris=pulumi.get(__ret__, 'file_uris'),
        id=pulumi.get(__ret__, 'id'),
        jar_uris=pulumi.get(__ret__, 'jar_uris'),
        labels=pulumi.get(__ret__, 'labels'),
        metadata=pulumi.get(__ret__, 'metadata'),
        name=pulumi.get(__ret__, 'name'),
        packages=pulumi.get(__ret__, 'packages'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        python=pulumi.get(__ret__, 'python'),
        resource_version=pulumi.get(__ret__, 'resource_version'),
        spark_conf=pulumi.get(__ret__, 'spark_conf'),
        spark_version=pulumi.get(__ret__, 'spark_version'),
        status=pulumi.get(__ret__, 'status'),
        updated_at=pulumi.get(__ret__, 'updated_at'))
def get_msp_spark_v1alpha1_session_output(id: Optional[pulumi.Input[Optional[str]]] = None,
                                          name: Optional[pulumi.Input[Optional[str]]] = None,
                                          parent_id: Optional[pulumi.Input[Optional[str]]] = None,
                                          opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetMspSparkV1alpha1SessionResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getMspSparkV1alpha1Session:getMspSparkV1alpha1Session', __args__, opts=opts, typ=GetMspSparkV1alpha1SessionResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetMspSparkV1alpha1SessionResult(
        created_at=pulumi.get(__response__, 'created_at'),
        description=pulumi.get(__response__, 'description'),
        driver=pulumi.get(__response__, 'driver'),
        executor=pulumi.get(__response__, 'executor'),
        file_uris=pulumi.get(__response__, 'file_uris'),
        id=pulumi.get(__response__, 'id'),
        jar_uris=pulumi.get(__response__, 'jar_uris'),
        labels=pulumi.get(__response__, 'labels'),
        metadata=pulumi.get(__response__, 'metadata'),
        name=pulumi.get(__response__, 'name'),
        packages=pulumi.get(__response__, 'packages'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        python=pulumi.get(__response__, 'python'),
        resource_version=pulumi.get(__response__, 'resource_version'),
        spark_conf=pulumi.get(__response__, 'spark_conf'),
        spark_version=pulumi.get(__response__, 'spark_version'),
        status=pulumi.get(__response__, 'status'),
        updated_at=pulumi.get(__response__, 'updated_at')))
