# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from . import _utilities
from . import outputs

__all__ = [
    'GetStorageV1BucketResult',
    'AwaitableGetStorageV1BucketResult',
    'get_storage_v1_bucket',
    'get_storage_v1_bucket_output',
]

@pulumi.output_type
class GetStorageV1BucketResult:
    """
    A collection of values returned by getStorageV1Bucket.
    """
    def __init__(__self__, created_at=None, id=None, labels=None, lifecycle_configuration=None, max_size_bytes=None, metadata=None, name=None, parent_id=None, resource_version=None, status=None, updated_at=None, versioning_policy=None):
        if created_at and not isinstance(created_at, str):
            raise TypeError("Expected argument 'created_at' to be a str")
        pulumi.set(__self__, "created_at", created_at)
        if id and not isinstance(id, str):
            raise TypeError("Expected argument 'id' to be a str")
        pulumi.set(__self__, "id", id)
        if labels and not isinstance(labels, dict):
            raise TypeError("Expected argument 'labels' to be a dict")
        pulumi.set(__self__, "labels", labels)
        if lifecycle_configuration and not isinstance(lifecycle_configuration, dict):
            raise TypeError("Expected argument 'lifecycle_configuration' to be a dict")
        pulumi.set(__self__, "lifecycle_configuration", lifecycle_configuration)
        if max_size_bytes and not isinstance(max_size_bytes, float):
            raise TypeError("Expected argument 'max_size_bytes' to be a float")
        pulumi.set(__self__, "max_size_bytes", max_size_bytes)
        if metadata and not isinstance(metadata, dict):
            raise TypeError("Expected argument 'metadata' to be a dict")
        pulumi.set(__self__, "metadata", metadata)
        if name and not isinstance(name, str):
            raise TypeError("Expected argument 'name' to be a str")
        pulumi.set(__self__, "name", name)
        if parent_id and not isinstance(parent_id, str):
            raise TypeError("Expected argument 'parent_id' to be a str")
        pulumi.set(__self__, "parent_id", parent_id)
        if resource_version and not isinstance(resource_version, float):
            raise TypeError("Expected argument 'resource_version' to be a float")
        pulumi.set(__self__, "resource_version", resource_version)
        if status and not isinstance(status, dict):
            raise TypeError("Expected argument 'status' to be a dict")
        pulumi.set(__self__, "status", status)
        if updated_at and not isinstance(updated_at, str):
            raise TypeError("Expected argument 'updated_at' to be a str")
        pulumi.set(__self__, "updated_at", updated_at)
        if versioning_policy and not isinstance(versioning_policy, str):
            raise TypeError("Expected argument 'versioning_policy' to be a str")
        pulumi.set(__self__, "versioning_policy", versioning_policy)

    @property
    @pulumi.getter(name="createdAt")
    def created_at(self) -> str:
        return pulumi.get(self, "created_at")

    @property
    @pulumi.getter
    def id(self) -> str:
        return pulumi.get(self, "id")

    @property
    @pulumi.getter
    def labels(self) -> Mapping[str, str]:
        return pulumi.get(self, "labels")

    @property
    @pulumi.getter(name="lifecycleConfiguration")
    def lifecycle_configuration(self) -> 'outputs.GetStorageV1BucketLifecycleConfigurationResult':
        return pulumi.get(self, "lifecycle_configuration")

    @property
    @pulumi.getter(name="maxSizeBytes")
    def max_size_bytes(self) -> float:
        return pulumi.get(self, "max_size_bytes")

    @property
    @pulumi.getter
    def metadata(self) -> 'outputs.GetStorageV1BucketMetadataResult':
        return pulumi.get(self, "metadata")

    @property
    @pulumi.getter
    def name(self) -> str:
        return pulumi.get(self, "name")

    @property
    @pulumi.getter(name="parentId")
    def parent_id(self) -> str:
        return pulumi.get(self, "parent_id")

    @property
    @pulumi.getter(name="resourceVersion")
    def resource_version(self) -> float:
        return pulumi.get(self, "resource_version")

    @property
    @pulumi.getter
    def status(self) -> 'outputs.GetStorageV1BucketStatusResult':
        return pulumi.get(self, "status")

    @property
    @pulumi.getter(name="updatedAt")
    def updated_at(self) -> str:
        return pulumi.get(self, "updated_at")

    @property
    @pulumi.getter(name="versioningPolicy")
    def versioning_policy(self) -> str:
        return pulumi.get(self, "versioning_policy")


class AwaitableGetStorageV1BucketResult(GetStorageV1BucketResult):
    # pylint: disable=using-constant-test
    def __await__(self):
        if False:
            yield self
        return GetStorageV1BucketResult(
            created_at=self.created_at,
            id=self.id,
            labels=self.labels,
            lifecycle_configuration=self.lifecycle_configuration,
            max_size_bytes=self.max_size_bytes,
            metadata=self.metadata,
            name=self.name,
            parent_id=self.parent_id,
            resource_version=self.resource_version,
            status=self.status,
            updated_at=self.updated_at,
            versioning_policy=self.versioning_policy)


def get_storage_v1_bucket(id: Optional[str] = None,
                          name: Optional[str] = None,
                          parent_id: Optional[str] = None,
                          opts: Optional[pulumi.InvokeOptions] = None) -> AwaitableGetStorageV1BucketResult:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke('nebius:index/getStorageV1Bucket:getStorageV1Bucket', __args__, opts=opts, typ=GetStorageV1BucketResult, package_ref=_utilities.get_package()).value

    return AwaitableGetStorageV1BucketResult(
        created_at=pulumi.get(__ret__, 'created_at'),
        id=pulumi.get(__ret__, 'id'),
        labels=pulumi.get(__ret__, 'labels'),
        lifecycle_configuration=pulumi.get(__ret__, 'lifecycle_configuration'),
        max_size_bytes=pulumi.get(__ret__, 'max_size_bytes'),
        metadata=pulumi.get(__ret__, 'metadata'),
        name=pulumi.get(__ret__, 'name'),
        parent_id=pulumi.get(__ret__, 'parent_id'),
        resource_version=pulumi.get(__ret__, 'resource_version'),
        status=pulumi.get(__ret__, 'status'),
        updated_at=pulumi.get(__ret__, 'updated_at'),
        versioning_policy=pulumi.get(__ret__, 'versioning_policy'))
def get_storage_v1_bucket_output(id: Optional[pulumi.Input[Optional[str]]] = None,
                                 name: Optional[pulumi.Input[Optional[str]]] = None,
                                 parent_id: Optional[pulumi.Input[Optional[str]]] = None,
                                 opts: Optional[Union[pulumi.InvokeOptions, pulumi.InvokeOutputOptions]] = None) -> pulumi.Output[GetStorageV1BucketResult]:
    """
    Use this data source to access information about an existing resource.
    """
    __args__ = dict()
    __args__['id'] = id
    __args__['name'] = name
    __args__['parentId'] = parent_id
    opts = pulumi.InvokeOutputOptions.merge(_utilities.get_invoke_opts_defaults(), opts)
    __ret__ = pulumi.runtime.invoke_output('nebius:index/getStorageV1Bucket:getStorageV1Bucket', __args__, opts=opts, typ=GetStorageV1BucketResult, package_ref=_utilities.get_package())
    return __ret__.apply(lambda __response__: GetStorageV1BucketResult(
        created_at=pulumi.get(__response__, 'created_at'),
        id=pulumi.get(__response__, 'id'),
        labels=pulumi.get(__response__, 'labels'),
        lifecycle_configuration=pulumi.get(__response__, 'lifecycle_configuration'),
        max_size_bytes=pulumi.get(__response__, 'max_size_bytes'),
        metadata=pulumi.get(__response__, 'metadata'),
        name=pulumi.get(__response__, 'name'),
        parent_id=pulumi.get(__response__, 'parent_id'),
        resource_version=pulumi.get(__response__, 'resource_version'),
        status=pulumi.get(__response__, 'status'),
        updated_at=pulumi.get(__response__, 'updated_at'),
        versioning_policy=pulumi.get(__response__, 'versioning_policy')))
