# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins as _builtins
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

addressOptions: Optional[str]
"""
Set specific options for each address. Use "\\*" to set them for all addresses at once. Empty options will result in
default TLS connection for this address, thus overriding "\\*".
"""

addressTemplate: Optional[str]
"""
address template (overrides address_template_env)
"""

addressTemplateEnv: Optional[str]
"""
env variable name to obtain address template in form of `FIND=REPLACE`
"""

domain: Optional[str]
"""
custom domain name (overrides domain_env)
"""

domainEnv: Optional[str]
"""
env variable name to obtain custom domain name
"""

moduleName: Optional[str]
"""
it is suggested to set this value to your module name if the provider is initialized in one, does not affect any
behaviors
"""

noCredentials: Optional[bool]
"""
do not authenticate
"""

parentId: Optional[str]
"""
Parent ID if it is not read from the profile, or if you want to overwrite it.
"""

profile: Optional[str]
"""
Reads profile from the CLI config.
"""

resolvers: Optional[str]
"""
resolver map of type `[pattern|service_id]->address`
"""

resolversEnv: Optional[str]
"""
env variable name that holds resolver map (may be set alongside resolvers)
"""

serviceAccount: Optional[str]
"""
sets service account credentials (is overridden by token)
"""

token: Optional[str]
"""
authenticate using this IAM token
"""

versionedEphemeralValues: Optional[str]
"""
A map of all ephemeral values that will be passed to nebius.Hash for hashing
"""

