# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities

__all__ = [
    'AddressOptions',
    'AddressTemplate',
    'ServiceAccount',
]

@pulumi.output_type
class AddressOptions(dict):
    def __init__(__self__, *,
                 insecure: Optional[bool] = None,
                 no_tls_verify: Optional[bool] = None):
        """
        :param bool insecure: use plain http connection
        :param bool no_tls_verify: don't verify TLS certificates
        """
        if insecure is not None:
            pulumi.set(__self__, "insecure", insecure)
        if no_tls_verify is not None:
            pulumi.set(__self__, "no_tls_verify", no_tls_verify)

    @property
    @pulumi.getter
    def insecure(self) -> Optional[bool]:
        """
        use plain http connection
        """
        return pulumi.get(self, "insecure")

    @property
    @pulumi.getter(name="noTlsVerify")
    def no_tls_verify(self) -> Optional[bool]:
        """
        don't verify TLS certificates
        """
        return pulumi.get(self, "no_tls_verify")


@pulumi.output_type
class AddressTemplate(dict):
    def __init__(__self__, *,
                 find: str,
                 replace: str):
        pulumi.set(__self__, "find", find)
        pulumi.set(__self__, "replace", replace)

    @property
    @pulumi.getter
    def find(self) -> str:
        return pulumi.get(self, "find")

    @property
    @pulumi.getter
    def replace(self) -> str:
        return pulumi.get(self, "replace")


@pulumi.output_type
class ServiceAccount(dict):
    def __init__(__self__, *,
                 account_id: Optional[str] = None,
                 account_id_env: Optional[str] = None,
                 credentials_file: Optional[str] = None,
                 credentials_file_env: Optional[str] = None,
                 private_key: Optional[str] = None,
                 private_key_file: Optional[str] = None,
                 private_key_file_env: Optional[str] = None,
                 public_key_id: Optional[str] = None,
                 public_key_id_env: Optional[str] = None):
        """
        :param str account_id: service account ID (overrides account_id_env)
        :param str account_id_env: env var containing service account ID
        :param str credentials_file: file path of the service account credentials file (overrides credentials_file_env)
               You can set this file instead of other parameters here, it will silently override them.
        :param str credentials_file_env: env var containing file path of the service account credentials, same as credentials_file
        :param str private_key: private key (overrides private_key_file and private_key_file_env)
        :param str private_key_file: file path of the service account private key (overrides private_key_file_env)
        :param str private_key_file_env: env var containing file path of the service account private key
        :param str public_key_id: service account public key ID (overrides public_key_id_env)
        :param str public_key_id_env: env var containing service account public key ID
        """
        if account_id is not None:
            pulumi.set(__self__, "account_id", account_id)
        if account_id_env is not None:
            pulumi.set(__self__, "account_id_env", account_id_env)
        if credentials_file is not None:
            pulumi.set(__self__, "credentials_file", credentials_file)
        if credentials_file_env is not None:
            pulumi.set(__self__, "credentials_file_env", credentials_file_env)
        if private_key is not None:
            pulumi.set(__self__, "private_key", private_key)
        if private_key_file is not None:
            pulumi.set(__self__, "private_key_file", private_key_file)
        if private_key_file_env is not None:
            pulumi.set(__self__, "private_key_file_env", private_key_file_env)
        if public_key_id is not None:
            pulumi.set(__self__, "public_key_id", public_key_id)
        if public_key_id_env is not None:
            pulumi.set(__self__, "public_key_id_env", public_key_id_env)

    @property
    @pulumi.getter(name="accountId")
    def account_id(self) -> Optional[str]:
        """
        service account ID (overrides account_id_env)
        """
        return pulumi.get(self, "account_id")

    @property
    @pulumi.getter(name="accountIdEnv")
    def account_id_env(self) -> Optional[str]:
        """
        env var containing service account ID
        """
        return pulumi.get(self, "account_id_env")

    @property
    @pulumi.getter(name="credentialsFile")
    def credentials_file(self) -> Optional[str]:
        """
        file path of the service account credentials file (overrides credentials_file_env)
        You can set this file instead of other parameters here, it will silently override them.
        """
        return pulumi.get(self, "credentials_file")

    @property
    @pulumi.getter(name="credentialsFileEnv")
    def credentials_file_env(self) -> Optional[str]:
        """
        env var containing file path of the service account credentials, same as credentials_file
        """
        return pulumi.get(self, "credentials_file_env")

    @property
    @pulumi.getter(name="privateKey")
    def private_key(self) -> Optional[str]:
        """
        private key (overrides private_key_file and private_key_file_env)
        """
        return pulumi.get(self, "private_key")

    @property
    @pulumi.getter(name="privateKeyFile")
    def private_key_file(self) -> Optional[str]:
        """
        file path of the service account private key (overrides private_key_file_env)
        """
        return pulumi.get(self, "private_key_file")

    @property
    @pulumi.getter(name="privateKeyFileEnv")
    def private_key_file_env(self) -> Optional[str]:
        """
        env var containing file path of the service account private key
        """
        return pulumi.get(self, "private_key_file_env")

    @property
    @pulumi.getter(name="publicKeyId")
    def public_key_id(self) -> Optional[str]:
        """
        service account public key ID (overrides public_key_id_env)
        """
        return pulumi.get(self, "public_key_id")

    @property
    @pulumi.getter(name="publicKeyIdEnv")
    def public_key_id_env(self) -> Optional[str]:
        """
        env var containing service account public key ID
        """
        return pulumi.get(self, "public_key_id_env")


