# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import copy
import warnings
import sys
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
if sys.version_info >= (3, 11):
    from typing import NotRequired, TypedDict, TypeAlias
else:
    from typing_extensions import NotRequired, TypedDict, TypeAlias
from .. import _utilities
from . import outputs

import types

__config__ = pulumi.Config('nebius')


class _ExportableConfig(types.ModuleType):
    @property
    def address_options(self) -> Optional[str]:
        """
        Set specific options for each address. Use "\\*" to set them for all addresses at once. Empty options will result in
        default TLS connection for this address, thus overriding "\\*".
        """
        return __config__.get('addressOptions')

    @property
    def address_template(self) -> Optional[str]:
        """
        address template (overrides address_template_env)
        """
        return __config__.get('addressTemplate')

    @property
    def address_template_env(self) -> Optional[str]:
        """
        env variable name to obtain address template in form of `FIND=REPLACE`
        """
        return __config__.get('addressTemplateEnv')

    @property
    def domain(self) -> Optional[str]:
        """
        custom domain name (overrides domain_env)
        """
        return __config__.get('domain')

    @property
    def domain_env(self) -> Optional[str]:
        """
        env variable name to obtain custom domain name
        """
        return __config__.get('domainEnv')

    @property
    def insecure(self) -> Optional[bool]:
        return __config__.get_bool('insecure')

    @property
    def insecure_addresses(self) -> Optional[str]:
        return __config__.get('insecureAddresses')

    @property
    def module_name(self) -> Optional[str]:
        """
        it is suggested to set this value to your module name if the provider is initialized in one, does not affect any
        behaviors
        """
        return __config__.get('moduleName')

    @property
    def no_credentials(self) -> Optional[bool]:
        """
        do not authenticate
        """
        return __config__.get_bool('noCredentials')

    @property
    def resolvers(self) -> Optional[str]:
        """
        resolver map of type `[pattern|service_id]->address`
        """
        return __config__.get('resolvers')

    @property
    def resolvers_env(self) -> Optional[str]:
        """
        env variable name that holds resolver map (may be set alongside resolvers)
        """
        return __config__.get('resolversEnv')

    @property
    def service_account(self) -> Optional[str]:
        """
        sets service account credentials (is overridden by token)
        """
        return __config__.get('serviceAccount')

    @property
    def token(self) -> Optional[str]:
        """
        authenticate using this IAM token
        """
        return __config__.get('token')

